---
version: '3'

services:
  db:
    image: mdillon/postgis:11
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: osm
      POSTGRES_PASSWORD: osm
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
  # docker-compose run osm2pgsql
  osm2pgsql:
    build: ./osm2pgsql
    depends_on:
      - db
    entrypoint: bash
    volumes:
      - "./data/pbf:/pbf"
